markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]
webserver_headers:
  "Cross-Origin-Embedder-Policy":"require-corp"
  "Cross-Origin-Opener-Policy":"same-origin"
